TEMATICAS = [
    "cubismo", "surrealismo", "impresionismo", "modernismo", "minimalismo", "realismo", "expresionismo", "romanticismo", "barroco", "renacimiento",
    "gótico", "abstracto", "futurismo", "postimpresionismo", "pop art", "vanguardismo", "art déco", "dadaísmo", "constructivismo", "neoclasicismo",
    "naruto", "pokemon", "dragonball", "one piece", "bleach", "sailor moon", "gundam", "totoro", "digimon", "avatar",
    "steins gate", "cowboy bebop", "inuyasha", "yu-gi-oh", "evangelion", "samurai jack", "gravity falls", "rickmorty", "adventure time",
    "minecraft", "fortnite", "zelda", "metroid", "halo", "doom", "tetris", "pacman", "sonic", "overwatch",
    "fallout", "bioshock", "portal", "skyrim", "witcher", "counterstrike", "league", "valorant",
    "inception", "matrix", "gladiator", "titanic", "psycho", "casablanca", "interstellar", "gravity", "memento", "coco",
    "rocky", "frozen", "up", "alien", "terminator", "predator", "spectre", "labyrinth", "panlabyrinth", "serenity",
    "gatito", "felino", "minino", "bigote", "ronroneo", "garra", "miau",
    "cyberpunk", "steampunk", "vaporwave", "retrowave", "neon", "fantasía", "misterio", "espacial", "robot", "ninja",
    "samurai", "pirata", "espía", "detective", "alienígena", "mutante", "zombie", "vampiro", "bruja", "hechicero",
    "dragón", "unicornio", "sirena", "centauro", "minotauro", "fauno", "fénix", "kraken", "quimera", "gárgola",
    "sombra", "fantasma", "duende", "ogro", "elfo", "enano", "orco", "troll", "gnomo", "súcubo",
    "arcano", "mítico", "selvático", "ciber", "glitch", "pixelado", "monocromo", "luz", "destello", "eco",
    "fuego", "hielo", "rayo", "tormenta", "marea", "vórtice", "océano", "desierto", "selva", "montaña",
    "cielo", "espíritu", "magia", "tempestad", "huracán", "galaxia", "cometa", "estrella", "planeta", "nebulosa",
    "aurora", "cosmos", "orbita", "espiral", "infierno", "paraíso", "prisma", "destino", "sueño", "leyenda",
    "mito", "río", "llama", "cristal", "caverna", "templo", "ruina", "fortaleza", "castillo", "palacio",
    "mazmorra", "ciudad", "aldea", "pueblo", "bazar", "mercado", "universo", "fábula", "cuento", "mitología",
    "epopeya", "tragedia", "comedia", "drama", "opera", "balada", "sonata", "ritmo", "compás", "melodía",
    "armonía", "novela", "cómic", "manga", "anime", "pixel", "grafito", "acuarela", "óleo", "carbón",
    "pastel", "témpera", "murales", "graffiti", "estampa", "collage", "dibujo", "boceto", "ilustración", "escultura",
    "relieve", "pintura", "instalación", "performance", "minimal", "pop", "vintage", "geométrico", "figurativo", "realista",
    "fantástico", "lúdico", "conceptual", "visionario", "vision", "estructura", "forma", "color", "textura", "detalle",
    "estilo", "patrón", "motivo", "trazo", "línea", "espacio", "perspectiva", "equilibrio", "contraste", "simetría",
    "asimetría", "escena", "cultura", "historia", "saga", "paradoja", "enigma", "secreto", "brillo", "resplandor",
    "eclipse", "reflejo", "espejo", "oculto", "silueta", "borrón", "estela", "rumor", "susurro", "silencio",
    "grito", "alba", "crepúsculo", "amanecer", "anochecer", "medianoche", "ocaso", "camino", "sendero", "rastro",
    "huella", "carrera", "vuelo", "ascenso", "caída", "parque", "jardín", "bosque", "prado", "campo",
    "rural", "urbano", "metrópoli", "villa", "refugio", "aventura", "exploración", "descubrimiento", "viaje", "odisea",
    "expedición", "travesía", "conquista", "territorio", "dominio", "poder", "reino", "imperio", "dinastía", "legado",
    "origen", "génesis", "evolución", "revolución", "transformación", "metamorfosis", "mutación", "expansión", "colapso", "caos",
    "orden", "simbiosis", "contradicción", "dualidad", "infinito", "eternidad", "ciclo", "cambio", "dinámica", "estática",
    "vibración", "frecuencia", "sonido", "ruido", "suspiro", "latido", "pulsación", "alma", "corazón", "mente",
    "consciencia", "imaginación", "realidad", "ilusión", "simulación", "reflexión", "memoria", "olvido", "recuerdo", "pasado",
    "presente", "futuro", "tiempo", "dimensión", "paralelo", "alternativa", "eterno", "efímero", "efecto", "impacto",
    "presencia", "ausencia", "cumbre", "vértice", "borde", "límite", "frontera", "margen", "conflicto", "batalla",
    "duelo", "reto", "prueba", "enfrentamiento", "estrategia", "táctica", "combate", "fuerza", "habilidad", "destreza",
    "agilidad", "velocidad", "potencia", "energía", "magnetismo", "electricidad", "mecánica", "organismo", "sistema", "red",
    "nexo", "conexión", "enlace", "vínculo", "cadena", "bloque", "dígito", "código", "secuencia", "número",
    "símbolo", "icono", "emblema", "insignia", "sello", "marca", "firma", "logo", "vector", "fractura",
    "fisura", "brecha", "abismo", "vértigo", "precipicio", "cima", "pico", "cresta", "esencia",
    "misticismo", "sencillez", "elegancia", "vanguardia", "renovación", "innovación", "tradición", "patrimonio", "expresión", "impronta",
    "emoción", "pasión", "ardor", "fervor", "bravura", "osadía", "audacia", "vigor", "ímpetu", "coraje",
    "valentía", "resiliencia", "esperanza", "anhelo", "claridad", "oscuridad", "anarquía", "sutileza", "intensidad", "notoriedad",
    "epifanía", "revelación", "ocasión", "paradigma", "alegría", "melancolía", "distopía", "utopía", "aleatoriedad", "caudal",
    "flujo", "corriente", "torbellino", "remolino", "espuma", "oasis", "mirada", "cóndor", "águila", "lince",
    "tigre", "león", "pantera", "jirafa", "elefante", "rinoceronte", "hipopótamo", "cebra", "camaleón", "orquídea",
    "rosal", "margarita", "lirio", "jazmín", "magnolia", "olivo", "roble", "pino", "abeto", "cedro",
    "sauce", "aliso", "arce", "haya", "ébano", "mármol", "granito", "basalto", "cuarcita", "pizarra",
    "vidrio", "metal", "madera", "plástico", "papel", "tela", "cerámica"
]

PERSONAJES = [
    "Totoro", "No-Face", "Aang", "Link", "Zelda", "Pikachu", "D.Va", 
    "Finn", "Jake", "Steven Universe", "Garnet", "Pearl", "Amethist", "Howl", "Sophie", 
    "Kiki", "Haku", "Tracer", "Cloud Strife", "Korra", "Zuko", 
    "Marceline", "Princess Bubblegum", "Dipper", "Mabel", "Bill Cipher", 
    "Raven", "Starfire", "Miles Morales", "Gwen Stacy", "Jack Skellington", 
    "Coraline", "Woody", "Buzz Lightyear", "Hiccup", 
    "Toothless", "Geralt of Rivia", "Arthur Morgan", 
    "Frisk", "Sans", "Toriel", "The Knight", "Hornet", "Solaire", 
    "Artorias", "Steve", "Creeper", "Cuphead", "Mugman", "Ori", 
    "Amaterasu", "2B", "Alucard", "Trevor Belmont", "Levi Ackerman", 
    "Eren Yeager", "Nezuko", "Tanjiro", "Goku", "Vegeta", "Sailor Moon", 
    "Luffy", "Zoro", "Naruto", "Sasuke", "Hinata", "Edward Elric", 
    "Winry Rockbell", "Spike Spiegel", "Vash the Stampede", "GladOS", "Chell", 
    "Sakura", "Mikasa", "Eren", "Levi", "Master Chief", "Cortana", "Doomguy",
    "Samus Aran", "Kratos", "Ellie", "Nathan Drake", "Aloy", "Sackboy", "Ratchet",
    "Clank", "Jak", "Daxter", "Sly Cooper", "Carmelita Fox", "Detective Void", "Sonic", "Tails",
    "Knuckles", "Amy", "Dr. Eggman", "Shadow", "Rouge", "Silver", "Blaze", "Hatsune Miku", "Megurine Luka",
    "Kagamine Rin", "Kagamine Len", "Kaito", "Meiko", "Gumi", "Kasane Teto", "Fukase",
]